local_pool:
  servers:
    - name: local
      base_url: "http://manager:3000"
      performance: low
      capacity: 1

prod_pool:
  servers:
    - name: local
      base_url: "http://manager:3000"
      performance: low
      capacity: 1
    - name: standbim
      base_url: "http://standbim.com:3000"
      performance: high
      capacity: 2

