local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

minio_test:
  service: S3
  access_key_id: <%= ENV['MINIO_ROOT_USER'] %>
  secret_access_key: <%= ENV['MINIO_ROOT_PASSWORD'] %>
  region: us-east-1
  bucket: test-bucket
  endpoint: <%= ENV['S3_ENDPOINT'] %>
  force_path_style: true

# TODO make separation for dev, test (change bucket)
minio:
  service: S3
  access_key_id: <%= ENV['MINIO_ROOT_USER'] %>
  secret_access_key: <%= ENV['MINIO_ROOT_PASSWORD'] %>
  region: us-east-1
  bucket: default-bucket
  endpoint: <%= ENV['S3_ENDPOINT'] %>
  force_path_style: true
