inherit_from: .rubocop_todo.yml

require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml
  rswag-specs: .rubocop_rspec_alias_config.yml
  pundit: config/rubocop-rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - bin/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 3

RSpec/MultipleMemoizedHelpers:
  Max: 10

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
