inherit_from: .rubocop_todo.yml

require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - bin/**/*
    - public/**/*
    - vendor/**/*
