version: "3.7"
services:
  backend:
    image: docker.webgears3d.com/hub3d/backend__dev
    environment:
      RAILS_ENV: development
    develop:
      watch:
        - path: ../../backend
          action: sync
          target: /backend
          ignore:
            - node_modules/
        - path: ../../backend/Gemfile.lock
          action: rebuild


  sidekiq:
    image: docker.webgears3d.com/hub3d/backend__dev
    environment:
      RAILS_ENV: development
    develop:
      watch:
        - path: ../../backend
          action: sync
          target: /backend
          ignore:
            - node_modules/

  postgres:
    ports:
      - "6432:5432"
