# Starts Vite-ruby dev server in rails container, see link below for more info
# https://evilmartians.com/chronicles/vite-lizing-rails-get-live-reload-and-hot-replacement-with-vite-ruby
# it overrides frontend service in hub.yml, because 23.02.2023 it's impossible to use external x-tension(
version: "3.7"
services:
  frontend:
    # Yes, it should be same image as backend__dev
    image: docker.webgears3d.com/hub3d/backend__dev
    build:
      args:
        RAILS_ENV: development
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    command: foreman start -f Procfile.dev
    ports:
      - "3036:3036"
    develop:
      watch:
        - path: ../../backend
          action: sync
          target: /backend
          ignore:
            - node_modules/
        - path: ../../backend/package-lock.json
          action: rebuild
