---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/conversions":
    parameters:
    - name: space-key
      in: header
      schema:
        type: string
    get:
      summary: List conversions
      operationId: getConversions
      description: List conversion tasks for user
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 325980e1-8668-4a08-ad4c-016e0caf2c6e
                space_id: 686f2adf-afa7-47ac-b870-2473c7917f4e
                space_key: c2tCJIR7
                status: inProgress
                progress: '0.0'
                start_time: 2024-05-17 15:16:15 UTC
                end_time: 
                conversion_job_id: 7251dd4a-8ea4-42b7-99a5-d2a39d4da4a8
                created_at: 2024-05-17 15:16:15 UTC
                updated_at: 2024-05-17 15:16:15 UTC
                meta:
                  dest_resource_id: f0f4fb90-9444-4ad4-adc8-cc86902d5e15
                  dest_version_id: 29dae1ef-5bc8-4328-aa97-a2298391e70a
              - id: c31dbaf6-d556-4fde-ace2-d18f381d2657
                space_id: 686f2adf-afa7-47ac-b870-2473c7917f4e
                space_key: c2tCJIR7
                status: inProgress
                progress: '0.0'
                start_time: 2024-05-17 15:16:15 UTC
                end_time: 
                conversion_job_id: 9f7cd105-8fcd-45ec-a56e-d35baeee2d6c
                created_at: 2024-05-17 15:16:15 UTC
                updated_at: 2024-05-17 15:16:15 UTC
                meta:
                  dest_resource_id: 73d34f83-f9bc-4e44-b7c9-342684ed2efb
                  dest_version_id: 9bb3d4fc-27e9-41c0-b895-42663b641747
              - id: caec0605-34a5-4937-a0bc-4bbf61d17f9b
                space_id: 686f2adf-afa7-47ac-b870-2473c7917f4e
                space_key: c2tCJIR7
                status: inProgress
                progress: '0.0'
                start_time: 2024-05-17 15:16:15 UTC
                end_time: 
                conversion_job_id: b3827e55-c43c-4aac-a0b7-6c61e346cbc5
                created_at: 2024-05-17 15:16:15 UTC
                updated_at: 2024-05-17 15:16:15 UTC
                meta:
                  dest_resource_id: a3fe3dfd-27d8-4366-a770-905fa63daa44
                  dest_version_id: 80cc924e-d0e0-41dd-8f23-9930312a78b6
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/conversion_task"
  "/api/v1/conversions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    - name: space-key
      in: header
      schema:
        type: string
    get:
      summary: show conversion
      operationId: getConversion
      description: Get description of Conversion Task
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 788430e4-7b41-46a9-8476-d40dd938dcc2
                space_id: cdf71234-a0b4-4575-838b-214c663001e0
                space_key: fo1Ac33u
                status: inProgress
                progress: '0.0'
                start_time: 2024-05-17 15:16:15 UTC
                end_time: 
                conversion_job_id: ed224433-2f36-4fed-85dd-8b6b52bec4d8
                created_at: 2024-05-17 15:16:15 UTC
                updated_at: 2024-05-17 15:16:15 UTC
                meta:
                  dest_resource_id: fb985128-8ade-44e1-9aed-f3ba953cbb2a
                  dest_version_id: f432619e-c247-4c96-ba4a-ab2f260a082b
              schema:
                "$ref": "#/components/schemas/conversion_task"
  "/api/v1/conversions/{id}/logs":
    parameters:
    - name: id
      in: path
      description: Conversion Task id
      required: true
      schema:
        type: string
    - name: space-key
      in: header
      schema:
        type: string
    get:
      summary: logs conversion
      operationId: getConversionLogs
      description: Get logs of Conversion Task (redirect to logs file)
      responses:
        '302':
          description: successful
  "/api/v1/op/convert-anonym":
    post:
      summary: convert_anonym op
      operationId: convertAnonym
      description: Start anonym conversion
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 23aad397-5a9a-486a-a747-082a2cce32c2
                space_id: 7b0b194d-2405-4f4e-817e-131593fdc082
                space_key: KKSwxXkj
                status: inProgress
                progress: '0.0'
                start_time: 2024-05-17 15:16:15 UTC
                end_time: 
                conversion_job_id: 5203a3db-504d-4d10-a4d1-54aa61607a45
                created_at: 2024-05-17 15:16:15 UTC
                updated_at: 2024-05-17 15:16:15 UTC
                meta:
                  dest_resource_id: 3dad384d-b342-4ed3-92ac-8478e2f73e1d
                  dest_version_id: 7cea597e-2bf8-4b86-bc8f-3aafa862dbfd
              schema:
                "$ref": "#/components/schemas/conversion_task"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - input_file
              properties:
                input_file:
                  type: string
                  description: Active Storage signeID
  "/users":
    post:
      summary: create registration
      operationId: signUp
      description: Sign up new user
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                user:
                  id: 0bbc235a-f3eb-42a9-a221-07f5d6833359
                  email: valid@email.com
                  created_at: '2024-05-17T15:16:15.934Z'
                  updated_at: '2024-05-17T15:16:15.934Z'
                  guest: false
                  uid: 
                  provider: 
                redirect_url: "/"
        '422':
          description: user already exist
          content:
            application/json:
              example:
                errors:
                  password_confirmation:
                  - doesn't match Password
                  password:
                  - is too short (minimum is 6 characters)
                  email:
                  - has already been taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - password
              - password_confirmation
              properties:
                email:
                  type: string
                  description: User's email
                password:
                  type: string
                  description: User's password
                password_confirmation:
                  type: string
                  description: password confirmation, should match password
  "/api/v1/resources/":
    parameters:
    - name: space-key
      in: header
      schema:
        type: string
    get:
      summary: list resources
      operationId: getResources
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 748b89bf-e3e3-4c9d-b31b-bbe2b3b86147
                space_id: 46045237-bc90-42e3-a324-6636b1c18af0
                space_key: BpLDbAVL
                name: tenetur.ifc
                created_at: 2024-05-17 15:16:16 UTC
                updated_at: 2024-05-17 15:16:16 UTC
                current_id: 
              - id: 506bd0f8-8181-4a9a-aec8-70c573e96ebc
                space_id: 46045237-bc90-42e3-a324-6636b1c18af0
                space_key: BpLDbAVL
                name: corporis.ifc
                created_at: 2024-05-17 15:16:16 UTC
                updated_at: 2024-05-17 15:16:16 UTC
                current_id: 
              - id: 74ddb500-0e91-4f9c-9f0c-1803e6771a80
                space_id: 46045237-bc90-42e3-a324-6636b1c18af0
                space_key: BpLDbAVL
                name: velit.ifc
                created_at: 2024-05-17 15:16:16 UTC
                updated_at: 2024-05-17 15:16:16 UTC
                current_id: 
  "/api/v1/resources/{id}":
    parameters:
    - name: id
      in: path
      description: Resource id
      required: true
      schema:
        type: string
    - name: space-key
      in: header
      schema:
        type: string
    get:
      summary: show resource
      operationId: getResource
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1467e853-436b-4ca6-afd9-dd403f342fc2
                space_id: 86322611-eefe-4c3f-bfdb-8e1cfa124a44
                space_key: kBjnrIlv
                name: ad.ifc
                created_at: 2024-05-17 15:16:16 UTC
                updated_at: 2024-05-17 15:16:16 UTC
                current_id: 
                permissions:
                  manage: true
                  share: true
                share_options:
                  link_access: none
                  space_id: 86322611-eefe-4c3f-bfdb-8e1cfa124a44
                  space_key: kBjnrIlv
                  has_link_password: false
  "/users/sign_in":
    post:
      summary: create session
      operationId: signIn
      description: Sign in user
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                user:
                  id: aa6d10f2-e828-4d80-9943-8c6d33e70079
                  email: lon@oberbrunner.example
                  created_at: '2024-05-17T15:16:16.073Z'
                  updated_at: '2024-05-17T15:16:16.073Z'
                  guest: false
                  uid: 
                  provider: 
                redirect_url: "/"
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                errors: not authenticated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - password
              properties:
                email:
                  type: string
                  description: User's email
                password:
                  type: string
                  description: User's password
  "/api/v1/resources/{id}/share-options":
    parameters:
    - name: id
      in: path
      description: Resource id
      required: true
      schema:
        type: string
    - name: space-key
      in: header
      schema:
        type: string
    get:
      summary: show resource's share_options
      operationId: getShareOptions
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                link_access: none
                space_id: 901d5f6e-7803-4a88-9ebe-f673595f8532
                space_key: HHIYqwLH
                has_link_password: false
    patch:
      summary: update resource's share_options
      operationId: updateShareOptions
      parameters: []
      responses:
        '204':
          description: successful
        '422':
          description: unprocessable entity
          content:
            application/json:
              example:
                errors:
                  link_password:
                  - is too short (minimum is 8 characters)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                link_access:
                  type: string
                  description: Resource view access by link, possible values :none,
                    :view
                  enum:
                  - none
                  - view
                link_password:
                  type: string
                  format: password
        required: true
  "/api/v1/resources/{id}/share-options/auth-password":
    parameters:
    - name: id
      in: path
      description: Resource id
      required: true
      schema:
        type: string
    - name: space-key
      in: header
      schema:
        type: string
    post:
      summary: enter password for resource share_option
      operationId: resourceAuthPassword
      parameters: []
      responses:
        '204':
          description: successful
        '422':
          description: forbidden
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                link_password:
                  type: string
                  format: password
        required: true
  "/api/v1/versions/{id}":
    parameters:
    - name: id
      in: path
      description: Version id
      required: true
      schema:
        type: string
    - name: space-key
      in: header
      schema:
        type: string
    get:
      summary: show version
      operationId: getVersion
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 05710e76-add4-4b54-b5b0-f99ec070daeb
                space_id: 1e68521f-a1aa-409f-b6fd-335a11c2dbce
                space_key: lByootqS
                resource_id: 6d230711-f5c1-46d2-8034-523b5059e008
                created_at: 2024-05-17 15:16:16 UTC
                updated_at: 2024-05-17 15:16:16 UTC
  "/api/v1/versions/{id}/files":
    parameters:
    - name: id
      in: path
      description: Version id
      required: true
      schema:
        type: string
    - name: space-key
      in: header
      schema:
        type: string
    get:
      summary: files version
      operationId: getVersionFiles
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
components:
  schemas:
    conversion_task:
      type: object
      properties:
        status:
          type: string
          example: finished
        progress:
          type: string
        start_time:
          type: string
          format: date_time
          nullable: true
        end_time:
          type: string
          format: date_time
          nullable: true
        conversion_job_id:
          type: string
          nullable: true
        created_at:
          type: string
          format: date_time
        updated_at:
          type: string
          format: date_time
        meta:
          type: object
          properties:
            dest_resource_id:
              type: string
              nullable: true
            dest_version_id:
              type: string
              nullable: true
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3050
