---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/conversions":
    get:
      summary: List conversions
      operationId: getConversions
      description: List conversion tasks for user
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 687bf591-c640-4d86-9dde-7314b37204e1
                status: inProgress
                progress: '0.0'
                start_time: 2024-03-12 17:49:35 UTC
                end_time: 
                conversion_job_id: 0d5a6bc2-faac-4e5b-ac2a-a4204c5799c8
                created_at: 2024-03-12 17:49:35 UTC
                updated_at: 2024-03-12 17:49:35 UTC
                meta:
                  dest_resource_id: 8d4845b5-1688-43de-a29e-8d044197f3bc
                  dest_version_id: 167cb6e1-14cc-4181-bbbd-ee16a6fd8736
              - id: fb25c0ee-7665-4a9f-814b-f2e42e0f558c
                status: inProgress
                progress: '0.0'
                start_time: 2024-03-12 17:49:35 UTC
                end_time: 
                conversion_job_id: f91ea2ef-29b7-49ba-a8d8-e96c1e45ffa2
                created_at: 2024-03-12 17:49:35 UTC
                updated_at: 2024-03-12 17:49:35 UTC
                meta:
                  dest_resource_id: 31773fad-e519-4697-8b84-cb213f6b6467
                  dest_version_id: 6720933b-5ad0-4eb9-9e3d-4363d5a5b9d9
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/conversion_task"
  "/api/v1/conversions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show conversion
      operationId: getConversion
      description: Get description of Conversion Task
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 50d8d747-4f60-430c-8e80-af1bbb7efc1b
                status: inProgress
                progress: '0.0'
                start_time: 2024-03-12 17:49:35 UTC
                end_time: 
                conversion_job_id: c356efb0-29c1-497b-8bef-fe545b655385
                created_at: 2024-03-12 17:49:35 UTC
                updated_at: 2024-03-12 17:49:35 UTC
                meta:
                  dest_resource_id: 4553f127-9124-46bc-83c7-d912e0921b39
                  dest_version_id: 4e203921-98f4-4e1e-bef5-495e5d05437f
              schema:
                "$ref": "#/components/schemas/conversion_task"
  "/api/v1/conversions/{id}/logs":
    parameters:
    - name: id
      in: path
      description: Conversion Task id
      required: true
      schema:
        type: string
    get:
      summary: logs conversion
      operationId: getConversionLogs
      description: Get logs of Conversion Task (redirect to logs file)
      responses:
        '302':
          description: successful
  "/api/v1/op/convert-anonym":
    post:
      summary: convert_anonym op
      operationId: convertAnonym
      description: Start anonym conversion
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 0a369426-c29e-43e9-8246-0411685975d9
                status: inProgress
                progress: '0.0'
                start_time: 2024-03-12 17:49:35 UTC
                end_time: 
                conversion_job_id: 641f21b2-9773-404d-8af2-5dcf041f2f19
                created_at: 2024-03-12 17:49:35 UTC
                updated_at: 2024-03-12 17:49:35 UTC
                meta:
                  dest_resource_id: 4b5d87c1-3ece-4baf-8d5c-455d6147e25c
                  dest_version_id: 5becb95c-36ee-4945-a320-6414767301bb
              schema:
                "$ref": "#/components/schemas/conversion_task"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - input_file
              properties:
                input_file:
                  type: string
                  description: Active Storage signeID
  "/api/v1/resources/{id}/share-options":
    parameters:
    - name: id
      in: path
      description: Resource id
      required: true
      schema:
        type: string
    get:
      summary: show resource's share_options
      operationId: getShareOptions
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                link_access: none
                has_link_password: false
    patch:
      summary: update resource's share_options
      operationId: updateShareOptions
      parameters: []
      responses:
        '204':
          description: successful
        '422':
          description: unprocessable entity
          content:
            application/json:
              example:
                errors:
                  link_password:
                  - is too short (minimum is 8 characters)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                link_access:
                  type: string
                  description: Resource view access by link, possible values :none,
                    :view
                  enum:
                  - none
                  - view
                link_password:
                  type: string
                  format: password
  "/api/v1/resources/{id}/share-options/auth-password":
    parameters:
    - name: id
      in: path
      description: Resource id
      required: true
      schema:
        type: string
    post:
      summary: enter password for resource share_option
      operationId: resourceAuthPassword
      parameters: []
      responses:
        '204':
          description: successful
        '403':
          description: forbidden
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                link_password:
                  type: string
                  format: password
components:
  schemas:
    conversion_task:
      type: object
      properties:
        status:
          type: string
          example: finished
        progress:
          type: string
        start_time:
          type: string
          format: date_time
          nullable: true
        end_time:
          type: string
          format: date_time
          nullable: true
        conversion_job_id:
          type: string
          nullable: true
        created_at:
          type: string
          format: date_time
        updated_at:
          type: string
          format: date_time
        meta:
          type: object
          properties:
            dest_resource_id:
              type: string
              nullable: true
            dest_version_id:
              type: string
              nullable: true
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3050
